# 2 Computacional

In [1]:
import numpy as np
from numpy.linalg import inv, pinv
from scipy.linalg import lu

## 1. Crear una funcion que realice el proceso de ortogonalizacion de Gram-Schmidt.

In [2]:
def gram_schmidt(X):
    O = np.zeros(X.shape)
    for i in range(X.shape[1]):
        # orthogonalization
        vector = X[:, i]
        space = O[:, :i]
        projection = vector @ space
        vector = vector - np.sum(projection * space, axis=1)
        # normalization
        norm = np.sqrt(vector @ vector)
        vector /= abs(norm) < 1e-8 and 1 or norm
        
        O[:, i] = vector
    return O

### verifique que el problema 1.1 las columnas son linealmente independientes

In [3]:
exercise_1 = np.array([[6.0, -3, 2], [1, 2, 5.0], [2, -8, -1]])
b = np.array([0., 0., 0.])
x = np.linalg.solve(exercise_1, b)

Como el resultado del vector es 0 entonces las columnas son linealmente indenpendientes.

In [4]:
print(x)

[ 0. -0.  0.]


## 2. Realizar el problema 1.2 en el PC usando el proceso de ortogonalizacion de Gram-Schmidt programado en el punto anterior.

In [5]:
A = np.array([[4.0, 0.0, 1.0], [1, -5.0, 1.0], [6, 1.0, 0.0], [1, -1, -5]])
b = np.array([[9], [0] ,[0] ,[0]])
Q = gram_schmidt(A)
print("Q: ",np.round(Q, 3))
R = Q.T @ A
print("R:", np.round(R, 3))

Q:  [[ 0.544  0.     0.192]
 [ 0.136 -0.962  0.192]
 [ 0.816  0.192 -0.   ]
 [ 0.136 -0.192 -0.962]]
R: [[ 7.348  0.     0.   ]
 [ 0.     5.196  0.   ]
 [ 0.    -0.     5.196]]


In [6]:
side_rigth = Q.T@b
x = np.linalg.solve(R, side_rigth)
print(np.round(x, 3))

[[ 0.667]
 [-0.   ]
 [ 0.333]]


Adicionalmente encontrar la solucion usando x = (A<sup>T</sup>A)<sup>-1</sup>A<sup>T</sup>b.

In [7]:
x = inv((A.T@A))@A.T@b
print(x)

[[0.66666667]
 [0.        ]
 [0.33333333]]


Comparar si la matriz (A<sup>T</sup>A)<sup>-1</sup>A<sup>T</sup> corresponde a la pseudo inversa, tipicamente denotada como pinv en las librerias de algebra lineal

In [8]:
matrix = inv((A.T@A))@A.T
matrix_pseudo = pinv(A)
matrix = matrix.round(3)
matrix_pseudo = matrix_pseudo.round(3)
print("matrix:", matrix)
print("pseudo inversa:", matrix_pseudo)
if(np.alltrue(matrix == matrix_pseudo)):
    print ("Son iguales")
else:
    print("No son iguales")

matrix: [[ 0.074  0.019  0.111  0.019]
 [ 0.    -0.185  0.037 -0.037]
 [ 0.037  0.037  0.    -0.185]]
pseudo inversa: [[ 0.074  0.019  0.111  0.019]
 [-0.    -0.185  0.037 -0.037]
 [ 0.037  0.037  0.    -0.185]]
Son iguales


##  3. Realizar el problema 1.3 en el PC. Generar las matrices A11, A12 y A22 de manera aleatoria,           para p = 3 y q = 5. Verificar que se cumple la demonstracion

In [9]:
p = 3
q = 5
A11 = np.random.rand(p,p)
A12 = np.random.rand(p,q)
zeros = np.zeros((q,p))
A22 = np.random.rand(q,q)

A = np.block([[A11,A12],[zeros,A22]])
print("A: ", np.round(A,3))
temp = -inv(A11)@A12@inv(A22)
inv_A = np.block([[inv(A11), temp], [zeros, inv(A22)]],)
print("inv_A: ", np.round(inv_A,3))
print("A@inv_A = I")
I = A@inv_A
print("I :")
print(np.round(I,3))

A:  [[0.993 0.086 0.972 0.139 0.456 0.564 0.7   0.228]
 [0.347 0.89  0.65  0.678 0.938 0.501 0.318 0.019]
 [0.874 0.847 0.918 0.33  0.786 0.15  0.165 0.714]
 [0.    0.    0.    0.886 0.892 0.272 0.406 0.574]
 [0.    0.    0.    0.916 0.591 0.928 0.407 0.716]
 [0.    0.    0.    0.762 0.664 0.671 0.522 0.851]
 [0.    0.    0.    0.913 0.432 0.642 0.534 0.542]
 [0.    0.    0.    0.829 0.721 0.971 0.756 0.224]]
inv_A:  [[-1.446 -4.039  4.391  0.738  0.923 -6.159  0.539  5.058]
 [-1.353 -0.335  1.67  -1.45  -1.552  0.061  1.121  1.808]
 [ 2.626  4.156 -4.633 -0.072  0.43   4.598 -0.214 -6.384]
 [ 0.     0.     0.     0.838  0.76  -2.436  2.248 -0.765]
 [ 0.     0.     0.     1.325  0.532  0.128 -2.621  0.765]
 [ 0.     0.     0.    -0.838  1.808 -0.279 -1.306  0.594]
 [ 0.     0.     0.    -0.945 -3.561  2.292  1.707  0.955]
 [ 0.     0.     0.    -0.544 -0.337  2.072  0.013 -0.966]]
A@inv_A = I
I :
[[ 1.  0. -0. -0.  0.  0.  0. -0.]
 [ 0.  1.  0. -0.  0. -0.  0. -0.]
 [ 0.  0.  1. -0.  0

## 4. Determine la factorizaci´on LU de A cuando C = 1. Una matriz como A con tres diagonales diferentesde cero es llamada matriz tri-diagonal. Los factores L y U son matrices bi-diagonales.

In [10]:
C = 1
diag_i = 1+2*C
diag_e = -C
row_1 = [diag_i, diag_e, 0     , 0      ,   0  ]
row_2 = [diag_e, diag_i, diag_e, 0      ,   0  ]
row_3 = [0     , diag_e, diag_i, diag_e ,   0  ]
row_4 = [0     , 0     , diag_e, diag_i, diag_e]
row_5 = [0     , 0     , 0     , diag_e, diag_i]

A = np.array([row_1, row_2, row_3,row_4,row_5])
print(A)

[[ 3 -1  0  0  0]
 [-1  3 -1  0  0]
 [ 0 -1  3 -1  0]
 [ 0  0 -1  3 -1]
 [ 0  0  0 -1  3]]


In [11]:
P, L, U = lu(A)

In [12]:
print("L: ", L)
print("U: ", U)

L:  [[ 1.          0.          0.          0.          0.        ]
 [-0.33333333  1.          0.          0.          0.        ]
 [ 0.         -0.375       1.          0.          0.        ]
 [ 0.          0.         -0.38095238  1.          0.        ]
 [ 0.          0.          0.         -0.38181818  1.        ]]
U:  [[ 3.         -1.          0.          0.          0.        ]
 [ 0.          2.66666667 -1.          0.          0.        ]
 [ 0.          0.          2.625      -1.          0.        ]
 [ 0.          0.          0.          2.61904762 -1.        ]
 [ 0.          0.          0.          0.          2.61818182]]


In [13]:
def lu_solve(L, U, b):
    # Ly = b
    y = np.linalg.solve(L, b)
    x = np.linalg.solve(U, y)
    return x

In [14]:
C = 1 
t0=[10, 12, 12, 12, 10]
t=[]
t.append(t0)
print("t[%s]: "% (0), t[0])
for k in range(4):
    t.append(lu_solve(L,U,t[k]))
    print("t[%s]: "% (k+1), np.round(t[k+1],3))

t[0]:  [10, 12, 12, 12, 10]
t[1]:  [ 6.556  9.667 10.444  9.667  6.556]
t[2]:  [4.741 7.667 8.593 7.667 4.741]
t[3]:  [3.599 6.056 6.901 6.056 3.599]
t[4]:  [2.792 4.778 5.486 4.778 2.792]
