In [5]:
A = [[ 4, 0 ,1], [ 1, -5 , 1] , [ 6, 1 ,0], [1, -1, -5]]

In [12]:
import numpy as np

In [14]:
q, r = np.linalg.qr(A)


In [62]:
q

array([[-5.44331054e-01, -2.14318987e-17,  1.92450090e-01],
       [-1.36082763e-01, -9.62250449e-01,  1.92450090e-01],
       [-8.16496581e-01,  1.92450090e-01,  1.38777878e-17],
       [-1.36082763e-01, -1.92450090e-01, -9.62250449e-01]])

In [17]:
print(r)

[[-7.34846923e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  5.19615242e+00  1.11022302e-16]
 [ 0.00000000e+00  0.00000000e+00  5.19615242e+00]]


In [66]:
q_t =np.transpose(q)
q_t

array([[-5.44331054e-01, -1.36082763e-01, -8.16496581e-01,
        -1.36082763e-01],
       [-2.14318987e-17, -9.62250449e-01,  1.92450090e-01,
        -1.92450090e-01],
       [ 1.92450090e-01,  1.92450090e-01,  1.38777878e-17,
        -9.62250449e-01]])

In [67]:
b=[[9],[0],[0],[0]]
#b=np.transpose(b)

In [68]:
np.shape(b)

(4, 1)

In [69]:
np.shape(q_t)

(3, 4)

In [70]:
result = q_t@b

In [71]:
result

array([[-4.89897949e+00],
       [-1.92887088e-16],
       [ 1.73205081e+00]])

In [73]:
x=[[2/3],[0],[1/3]]

In [75]:
np.array(A)@x

array([[ 3.],
       [ 1.],
       [ 4.],
       [-1.]])